import { ROLES } from './roles';
import { ROUTES } from './routes';

export const ACCESS_CONFIG: Record<string, string[]> = {
  // Shared Routes
  [ROUTES.PUBLIC.HOME]: [], // Empty means public
  
  // Member Access
  [ROUTES.MEMBER.DASHBOARD]: [ROLES.MEMBER],
  [ROUTES.MEMBER.ANNOUNCEMENTS]: [ROLES.MEMBER],
  [ROUTES.MEMBER.PROFILE]: [ROLES.MEMBER],
  [ROUTES.MEMBER.SETTINGS]: [ROLES.MEMBER],

  // Admin Wilayah Access
  [ROUTES.ADMIN_WILAYAH.DASHBOARD]: [ROLES.ADMIN_WILAYAH],
  [ROUTES.ADMIN_WILAYAH.MEMBERS]: [ROLES.ADMIN_WILAYAH],
  [ROUTES.ADMIN_WILAYAH.ANNOUNCEMENTS]: [ROLES.ADMIN_WILAYAH],
  [ROUTES.ADMIN_WILAYAH.REGION_PROFILE]: [ROLES.ADMIN_WILAYAH],
  [ROUTES.ADMIN_WILAYAH.PROFILE]: [ROLES.ADMIN_WILAYAH],
  [ROUTES.ADMIN_WILAYAH.SETTINGS]: [ROLES.ADMIN_WILAYAH],
  [ROUTES.ADMIN_WILAYAH.MY_ANNOUNCEMENTS]: [ROLES.ADMIN_WILAYAH],

  // Admin Pusat Access
  [ROUTES.ADMIN_PUSAT.DASHBOARD]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.MEMBERS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.APPROVALS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.PAYMENTS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.REGIONS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.ANNOUNCEMENTS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.CMS_HERO]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.CMS_GURU_BESAR]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.CMS_NEWS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.CMS_ARTICLES]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.CMS_GALLERY]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.PAYMENT_SETTINGS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.PROFILE]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.SETTINGS]: [ROLES.ADMIN_PUSAT],
  [ROUTES.ADMIN_PUSAT.MY_ANNOUNCEMENTS]: [ROLES.ADMIN_PUSAT],

  // Super Admin Access
  [ROUTES.SUPER_ADMIN.DASHBOARD]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.USERS]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.ACTION_MATRIX]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.FEATURE_CONTROL]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.IMPERSONATE]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.AUDIT_LOGS]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.BACKUP]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.SYSTEM_SETTINGS]: [ROLES.SUPER_ADMIN],
  [ROUTES.SUPER_ADMIN.PROFILE]: [ROLES.SUPER_ADMIN],
};

export const ACTION_ACCESS: Record<string, string[]> = {
  user_create: [ROLES.SUPER_ADMIN],
  user_delete: [ROLES.SUPER_ADMIN],
  member_approve: [ROLES.ADMIN_PUSAT],
  cms_delete: [ROLES.ADMIN_PUSAT],
  impersonate_start: [ROLES.SUPER_ADMIN],
  backup_download: [ROLES.SUPER_ADMIN],
};

export function canAction(userRole: string, action: string): boolean {
  return ACTION_ACCESS[action]?.includes(userRole) ?? false;
}

export const isRouteAllowed = (path: string, userRole: string): boolean => {
  // Find exact match or prefix match
  for (const [route, allowedRoles] of Object.entries(ACCESS_CONFIG)) {
    if (path === route || (route.includes(':') && path.startsWith(route.split(':')[0]))) {
      return allowedRoles.length === 0 || allowedRoles.includes(userRole);
    }
  }
  return true; // Default allow if not in config (or handle otherwise)
};
