import { ROLES } from './roles';

export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/tentang',
    BRANCHES: '/cabang',
    PUBLICATIONS: '/publikasi',
    PUBLICATION_DETAIL: '/publikasi/:id',
    GALLERY: '/galeri',
    VERIFICATION: '/verifikasi',
    PRIVACY: '/kebijakan-privasi',
    TERMS: '/syarat-ketentuan',
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    VERIFY_OTP: '/verify-otp',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
  },
  DASHBOARD: {
    [ROLES.MEMBER]: '/app/member/dashboard',
    [ROLES.ADMIN_WILAYAH]: '/app/admin-wilayah/dashboard',
    [ROLES.ADMIN_PUSAT]: '/app/admin-pusat/dashboard',
    [ROLES.SUPER_ADMIN]: '/app/super-admin/dashboard',
  },
  MEMBER: {
    DASHBOARD: '/app/member/dashboard',
    ANNOUNCEMENTS: '/app/member/announcements',
    PROFILE: '/app/member/profile',
    SETTINGS: '/app/member/settings',
  },
  ADMIN_WILAYAH: {
    DASHBOARD: '/app/admin-wilayah/dashboard',
    MEMBERS: '/app/admin-wilayah/members',
    ANNOUNCEMENTS: '/app/admin-wilayah/announcements',
    REGION_PROFILE: '/app/admin-wilayah/profile-wilayah',
    PROFILE: '/app/admin-wilayah/profile',
    SETTINGS: '/app/admin-wilayah/settings',
    MY_ANNOUNCEMENTS: '/app/admin-wilayah/my-announcements',
  },
  ADMIN_PUSAT: {
    DASHBOARD: '/app/admin-pusat/dashboard',
    MEMBERS: '/app/admin-pusat/members',
    APPROVALS: '/app/admin-pusat/members?tab=APPROVAL',
    PAYMENTS: '/app/admin-pusat/payments',
    REGIONS: '/app/admin-pusat/regions',
    ANNOUNCEMENTS: '/app/admin-pusat/announcements',
    CMS_HERO: '/app/admin-pusat/cms/hero-slider',
    CMS_GURU_BESAR: '/app/admin-pusat/cms/guru-besar',
    CMS_NEWS: '/app/admin-pusat/cms/news',
    CMS_ARTICLES: '/app/admin-pusat/cms/articles',
    CMS_GALLERY: '/app/admin-pusat/cms/gallery',
    PAYMENT_SETTINGS: '/app/admin-pusat/payment-settings',
    PROFILE: '/app/admin-pusat/profile',
    SETTINGS: '/app/admin-pusat/settings',
    MY_ANNOUNCEMENTS: '/app/admin-pusat/my-announcements',
  },
  SUPER_ADMIN: {
    DASHBOARD: '/app/super-admin/dashboard',
    USERS: '/app/super-admin/users',
    ACTION_MATRIX: '/app/super-admin/action-matrix',
    FEATURE_CONTROL: '/app/super-admin/feature-control',
    IMPERSONATE: '/app/super-admin/impersonate',
    AUDIT_LOGS: '/app/super-admin/audit-logs',
    BACKUP: '/app/super-admin/backup',
    SYSTEM_SETTINGS: '/app/super-admin/system-settings',
    PROFILE: '/app/super-admin/profile',
  },
};
